[package]
name = "test-suite"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
test-suite-chunk = { path = "../test-suite-chunk" }
test-suite-json = { path = "../test-suite-json" }
# rsjsonnet = "0.4.0" # for jsonnet support